# Generated by Django 4.2 on 2023-05-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='photo',
            new_name='image',
        ),
    ]
